baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Wiki Theme
theme: hugo-fresh-wiki

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
